services:
  backend:
    build:
      context: ./backend
      pull: true
      no_cache: false
    image: ponyfun-backend:latest
    ports:
      - "3005:3005"
    environment:
      - DATABASE_PATH=/app/data/ponyfun.db
    volumes:
      - ponyfun-db-data:/app/data
    networks:
      - ponyfun-net
    restart: always

  frontend:
    build:
      context: ./frontend
      pull: true
      no_cache: false
    image: ponyfun-frontend:latest
    ports:
      - "4201:80"
    networks:
      - ponyfun-net
    depends_on:
      - backend
    restart: always

volumes:
  ponyfun-db-data:


networks:
  ponyfun-net:
    driver: bridge
