services:
  backend:
    build: ./backend
    ports:
      - "3005:3005"
    environment:
      - DATABASE_PATH=/app/data/ponyfun.db
    volumes:
      - ponyfun-db-data:/app/data
    networks:
      - ponyfun-net
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "4201:80"
    networks:
      - ponyfun-net
    depends_on:
      - backend
    restart: always

volumes:
  ponyfun-db-data:


networks:
  ponyfun-net:
    driver: bridge
